= Renee Seet - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: AddressBook - Level 4
AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 6 kLoC.

*Code contributed*: [https://github.com/CS2103AUG2017-W15-B2/main/blob/master/collated/main/yilun-zhu.md[Functional code]] [https://github.com/CS2103AUG2017-W15-B2/main/blob/master/collated/test/yilun-zhu.md[Test code]] {give links to collated code files}

=== Enhancement Added: Mass Emailing

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=massemail]

#End of Extract#

---

==== Justification

A mass emailing function would allow to businesses to send monthly newsletters, greetings or reminders to all their customers. 
Furthermore, it would be more efficient if businesses can send to different group of customers, I decided to 
or reminders to all 
The mass emailling function w businesses to reach out to all their customers or to different group of customers easily.
Since user can add emails manually to the `To:` textbox, even with an invalid tag, user can still call the `EmailPanel` and send their emails through CYNC. 

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=massemail]

#End of Extract#

---

=== Enhancement Added: Add Joined Date

==== External behavior

---
#Start of Extract [from: User Guide]#


#End of Extract#

---

==== Justification



==== Implementation

---
#Start of Extract [from: Developer Guide]#


#End of Extract#

---


=== Enhancement Added: Login Page

I decided not to use the Login Page after I implemented it. As I realised that it led to much coupling which is undesirable.
I edited the test cases to go through the Login Page before every test. This cause the testcases to be dependent on the function.
Furthermore, it is not safe to store default password and username.

==== External behavior

---
#Start of Extract [from: User Guide]#


#End of Extract#

---

==== Justification

Customers' information are valuable and businesses would want to protect and store them safely. 
A Login Page on CYNC would deter unauthorised users to gain access to customers' data.
Furthermore, since both the Mass Emailing and the Calendar functions requires Google authentication, it can be done when logging in to CYNC.


==== Implementation

---

---


=== Enhancement Proposed: Add command `remark`

{Explain similar to the Undo/Redo feature above.}

=== Other contributions

* Solved bug for clear command #link:https://github.com/CS2103AUG2017-W15-B2/main/issues/60 
* pull request https://github.com/CS2103AUG2017-W15-B2/main/pull/80
* Updating User guide and developer guide

