= Zhu Yilun - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: CYNC
CYNC is an open-source software that helps small businesses to track and nurture relationships with customers. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 8 kLoC.

*Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] {give links to collated code files}

=== Enhancement Added: Find function improvements

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=findfunction]

#End of Extract#

---

==== Justification

This improvement is inspired by the search function in Gmail. I felt that Gmail's search function is very intuitive
for the user as it searches through all the fields in a single search bar. +
The original find function can only search by `Name`. As a user, I felt that the function is rather limited
and I wanted to filter people by other fields, such as people living in a
certain district. However, having separate search functions to search for the respective fields may be confusing for the
users. Therefore, I improved upon the current `find` function such that the users can use a single intuitive
search function that filters through all the fields.


==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=findfunction]

#End of Extract#

---

=== Enhancement Added: Calendar functions

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=findfunction]

include::../UserGuide.adoc[tag=calendar]

include::../UserGuide.adoc[tag=addEvent]


#End of Extract#

---

==== Justification

For businesses to reach out to all their customers or to different group of customers easily.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=calendar]

#End of Extract#

---

=== Enhancement Proposed: Add command `remark`

{Explain similar to the Undo/Redo feature above.}

=== Other contributions

* Wrote additional tests to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
