= Zhu Yilun - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: CYNC
CYNC is an open-source software that helps small businesses to track and nurture relationships with customers. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 8 kLoC.

*Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]]

=== Enhancement Added: Find function improvements

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=findfunction]

#End of Extract#

---

==== Justification

This improvement is inspired by the search function in Gmail. I felt that Gmail's search function is very intuitive
for the user as it searches through all the fields in a single search bar. +
The original find function can only search by `Name`. As a user, I felt that the function is rather limited
and I wanted to filter people by other fields, such as people living in a
certain district. However, having separate search functions to search for the respective fields may be confusing for the
users. Therefore, I improved upon the current `find` function such that the users can use a single intuitive
search function that filters through all the fields.


==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=findfunction]

#End of Extract#

---

=== Enhancement Added: Calendar functions

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=calendar]

include::../UserGuide.adoc[tag=addEvent]


#End of Extract#

---

==== Justification

To help the business owners' to manage their business schedule, for example a schedule of the upcoming tuition classes. Since
CYNC is developed as an application to help small business owners to manage their growing business, a scheduler function
such as the `calendar` function can help them manage their upcoming business events. +
As a user of the calendar function, I felt that it is troublesome to interact with the calendar just by clicking, as I would have
to scroll multiple times if I want to add an event few months in advance, and then scroll all the way back for my current schedule.
Therefore, I implemented the `addEvent` function. This allows the user to directly add an event to the google calendar without any
clicking or scrolling.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=calendar]

#End of Extract#

---

=== Enhancement Proposed: Add command `remark`

{Explain similar to the Undo/Redo feature above.}

=== Other contributions

* Wrote additional tests to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
